name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      mobile_release_created: ${{ steps.release.outputs['apps/mobile--release_created'] }}
      mobile_release_body: ${{ steps.release.outputs['apps/mobile--body'] }}

    steps:
      - name: Run Release Please
        id: release
        uses: googleapis/release-please-action@v5
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  mobile-production-build:
    # Update to major release instead of breaking change
    needs: release-please
    if: >
      needs.release-please.outputs.mobile_release_created == 'true' &&
      contains(needs.release-please.outputs.mobile_release_body, 'BREAKING CHANGES')
    uses: ./.github/workflows/mobile-build.yml
    with:
      profile: production
    secrets: inherit
